# Generated by Django 3.2.3 on 2021-05-27 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_auto_20210526_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='School',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models_app.school'),
        ),
    ]
