# Generated by Django 3.2.3 on 2021-05-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_auto_20210527_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='School',
            new_name='school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_resumption',
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(max_length=40),
        ),
    ]
